[[constraint]]
  branch = "master"
  name = "github.com/codeskyblue/kexec"

[[constraint]]
  name = "github.com/flosch/pongo2"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/glycerine/rbuf"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/jtblin/go-ldap-client"
  version = "0.0.3"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/qiniu/log"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/wfxiang08/cyutils"

[prune]
  go-tests = true
  unused-packages = true
