server:
  ldap:
    enabled: false
    host: 127.0.0.1
    base: ou=dev,dc=test,dc=org
    port: 10389
    use_ssl: false
    bind_dn: uid=bind,ou=dev,dc=test,dc=org
    bind_password: bind_account_password
    user_filter: (uid=%s)
    attributes:
    - givenName
    - sn
    - mail
    - uid
  addr: :11313
db:
  db_type: mysql
  db_dsn: root:@tcp(127.0.0.1:3306)/gosuv_db?tls=skip-verify&autocommit=true
host: test
admins:
- user1
